import Providers from "@/lib/Providers";
import "./globals.css";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import SessionProvider from "./../components/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <Providers>
      <SessionProvider session={session}>
        <html lang="en" data-theme="light">
          <body className={inter.className}>
            <main className="mx-auto">{children}</main>
          </body>
        </html>
      </SessionProvider>
    </Providers>
  );
}
